[package]
name = "olavm"
version = "0.1.0"
edition = "2021"
authors = ["olavm contributors"]
description = "Olavm's assembler and virtual machine cli"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.17"
